/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";


/**
 * @interface
 * An interface representing PageListItemDto.
 */
export interface PageListItemDto {
  /**
   * @member {string} id
   */
  id: string;
  /**
   * @member {string} code
   */
  code: string;
  /**
   * @member {string} title
   */
  title: string;
}

/**
 * @interface
 * An interface representing PageInput.
 */
export interface PageInput {
  /**
   * @member {string} code
   */
  code: string;
  /**
   * @member {string} title
   */
  title: string;
  /**
   * @member {string} body
   */
  body: string;
}

/**
 * @interface
 * An interface representing PageDto.
 */
export interface PageDto {
  /**
   * @member {string} id
   */
  id: string;
  /**
   * @member {string} code
   */
  code: string;
  /**
   * @member {string} title
   */
  title: string;
  /**
   * @member {string} body
   */
  body: string;
}

/**
 * @interface
 * An interface representing MyAPIOptions.
 * @extends ServiceClientOptions
 */
export interface MyAPIOptions extends ServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}

/**
 * @interface
 * An interface representing MyAPIAddPageOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface MyAPIAddPageOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {PageInput} [input]
   */
  input?: PageInput;
}

/**
 * @interface
 * An interface representing MyAPIUpdatePageOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface MyAPIUpdatePageOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {PageInput} [input]
   */
  input?: PageInput;
}

/**
 * Contains response data for the getPages operation.
 */
export type GetPagesResponse = Array<PageListItemDto> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PageListItemDto[];
    };
};

/**
 * Contains response data for the addPage operation.
 */
export type AddPageResponse = PageDto & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PageDto;
    };
};

/**
 * Contains response data for the getPage operation.
 */
export type GetPageResponse = PageDto & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PageDto;
    };
};

/**
 * Contains response data for the updatePage operation.
 */
export type UpdatePageResponse = PageDto & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: PageDto;
    };
};
