/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";


/**
 * @interface
 * An interface representing Xxx.
 */
export interface Xxx {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [surname]
   */
  surname?: string;
}

/**
 * @interface
 * An interface representing MyAPIOptions.
 * @extends ServiceClientOptions
 */
export interface MyAPIOptions extends ServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}

/**
 * Contains response data for the doStuff operation.
 */
export type DoStuffResponse = Array<Xxx> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Xxx[];
    };
};
